/**
 * Regenerates src/components/globe/cobeBundle.ts from the installed `cobe`
 * package. Run after bumping cobe:  node scripts/vendor-cobe.js
 *
 * cobe ships a single self-contained ESM file. The WebView that hosts the globe
 * has no module resolver and no network access, so the export statement is
 * rewritten to a window global and the whole thing is embedded as a string.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'node_modules/cobe/package.json'), 'utf8'));
const src = fs.readFileSync(path.join(root, 'node_modules/cobe/dist/index.esm.js'), 'utf8').trim();

const match = src.match(/export\s*\{\s*([A-Za-z_$][\w$]*)\s+as\s+default\s*\}\s*;?\s*$/);
if (!match) {
  console.error('cobe: could not find the trailing `export { X as default }`. Bundle format changed.');
  process.exit(1);
}

const body = `${src.slice(0, match.index)}window.createGlobe=${match[1]};`;
const escaped = body
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const out = `// Vendored from cobe@${pkg.version} (MIT, https://github.com/shuding/cobe).
// Generated by scripts/vendor-cobe.js — do not edit by hand.
// The ESM export is rewritten to a window global so the WebView can load it
// from a plain <script> tag with no module resolution or network access.

export default \`${escaped}\`;
`;

fs.writeFileSync(path.join(root, 'src/components/globe/cobeBundle.ts'), out);
console.log(`cobe@${pkg.version} vendored (binding: ${match[1]}, ${out.length} bytes)`);
